### ISSUE TITLE
apt update: E: The repository 'http://download.opensuse.org/repositories/home:/kernc:/xsuspender/xUbuntu_22.04  Release' no longer has a Release file.

### ISSUE THREAD

**Issue by pellaeon** [kernc/xsuspender#40] opened 2022-11-12 18:55 UTC
When I ran `apt update` on my Ubuntu 22.04 today, it complained:

`E: The repository 'http://download.opensuse.org/repositories/home:/kernc:/xsuspender/xUbuntu_22.04  Release' no longer has a Release file.`

This seems to be caused by Open Build Service requiring additional project configurations to select preferred dependencies. See the [Monitor page](https://build.opensuse.org/project/monitor/home:kernc:xsuspender), it says:

`have choice for libjpeg-dev needed by libgdk-pixbuf-2.0-dev: libjpeg-dev libjpeg-turbo8-dev, have choice for libjpeg-dev needed by libtiff-dev: libjpeg-dev libjpeg-turbo8-dev`

**Comment by kernc** [comment] 2022-11-13 15:17
Duplicate of https://github.com/kernc/xsuspender/issues/37 and https://github.com/openSUSE/open-build-service/issues/10773. You should find this resolved now.

**Closed by kernc** 2022-11-13 15:17 UTC

**Comment by pellaeon** [comment] 2022-11-14 14:13
Confirmed, works for me, thanks!
